### ISSUE TITLE
Support for other functions

### ISSUE THREAD

**Issue by Reploidsham** [CMoyuer/VRChatAvatarSDK3Container#1]
Considering a lot of this will be useful for porting to other systems, the tools other people make are reliant on particular namespaces that don't exist within the tool and should be considered adding, such as VRCAvatarParameterDriver.

It might be good to make that a plugin as well. This is somewhat necessary in order to port from things like "Hai's combo gesture expressions", "Fluff's toolbox", and "Pumkin's tools" as of now.

**Comment by CMoyuer** [comment]
Thanks for the feedback, I will support state behaviors in the next version

**Comment by Reploidsham** [comment]
I'm sorry I can't help more, I appreciate you doing that. I'll let a couple
other people I know know about it.
